name: monomer
version: 0.1.0
author: Sergey Akopkokhyants
description: A Monomer is next generation of Dart Web Tookit ported to Polymer library.
homepage: https://github.com/akserg/monomer
dependencies:
  browser: ">= 0.8.1"
  polymer: ">= 0.8.1"
