name: monomer
version: 0.1.1
author: Sergey Akopkokhyants <akserg@gmail.com>
description: A Monomer is a set of data centric UI components that may bind to other components to form a Polymer.
homepage: https://github.com/akserg/monomer
environment:
  sdk: '>=0.8.10+10 <2.0.0'
dependencies:
  log4dart: '>=1.4.11'
  polymer: '>=0.8.10+10 <2.0.0'
dev_dependencies:
  hop: 0.27.0
  bot_test: any
  unittest: '>=0.8.10+10 <2.0.0'
