name: monomer
version: 0.1.3
author: Sergey Akopkokhyants <akserg@gmail.com>
description: A Monomer is a set of data centric UI components that may bind to other components to form a Polymer.
homepage: https://github.com/akserg/monomer
environment:
  sdk: '>=0.8.10+10 <2.0.0'
dependencies:
  log4dart: '>=1.4.11'
  polymer: '>=0.9.0 <2.0.0'
dev_dependencies:
  unittest: '>=0.9.0 <2.0.0'
transformers:
- polymer:
    entry_points: web/index.html