name: monomer
version: 0.1.0
author: Sergey Akopkokhyants <akserg@gmail.com>
description: A Monomer is a set of data centric UI components that may bind to other components to form a Polymer.
homepage: https://github.com/akserg/monomer
environment:
  sdk: ">=0.8.10"
dependencies:
  polymer: ">=0.8.10"
dev_dependencies:
  hop: "0.27.0"
  unittest: ">=0.8.10"
  bot_test: any

